### ISSUE TITLE
Does this work on .net 4.52?

### ISSUE THREAD

**Issue by 3green** [GenuineChannels/GenuineChannels#3] opened 2017-04-22 11:15 UTC
On ghttp am getting 
the remote server returned 500 internal server error

at 	
				using (HttpWebResponse httpWebResponse = (HttpWebResponse) httpWebRequest.GetResponse())

in private HttpClientConnection LowLevel_OpenConnection()

Thanks

**Comment by yallie** [comment] 2017-04-22 17:51
I myself don't use ghttp, but I'm sure it should work on .NET 4.5.2.
Don't quite understand the structure of your application.
What server you're connecting to? Can you post a minimal code snippet 
to reproduce the issue (something [like this one](https://gist.github.com/yallie/483f5773ef2372a3cc493a2b3a43a9e2))?

On .NET, HTTP 500 error usually means that the server throws an exception
while processing your request. So I guess to investigate what's that, you need
to attach the debugger to the server process and catch the exception.

**Comment by 3green** [comment] 2017-04-24 11:18
Hi Yallie, Thankyou for the reply. I have been following the instructions in the GC Programming Guide.pdf pg 71,72.

Got the chat server sample working on tcp but not ghttp.
So have 3 projs 1 server, 1 client & class lib of IService       
>> POCKnownobjects2

    public interface IService
    {
        string Greeting(string s);
    }

>> POCGCServer2:
 static void Main(string[] args)
        {
            try
            {
                RunServer();
            }
            catch (Exception exy)
            {
            }
        }
 private static void RegisterChannel()
        {
            var props = new Dictionary<string, string>
            {
                { "name", "ghttp" },
                { "priority", "100" }
            };
            var channel = new GenuineHttpServerChannel(props, null, null);
            ChannelServices.RegisterChannel(channel, false);
        }
        private static void RunServer()
        {
            RegisterChannel();

          //  WellKnownServiceTypeEntry WKSTE = new   //WellKnownServiceTypeEntry(typeof(POCKnownObjects2.IService), "service.rem", //WellKnownObjectMode.Singleton);
       //     RemotingConfiguration.RegisterWellKnownServiceType(WKSTE);
            var service = new Service();
            var objref = RemotingServices.Marshal(service, "service.rem");     
            Console.WriteLine("Server started. Press ENTER to quit");
            Console.ReadLine();
        }

        internal class Service : MarshalByRefObject, IService
        {
            public string Greeting(string s)
            {
                var result = $"Hello, {s}!";
                Console.WriteLine("Replying to client: {0}", result);
                return result;
            }
        }

>> POCGCClient2:
        static void Main(string[] args)
        {
            RunClient();
        }

       private static void RegisterChannel()
        {
            var props = new Dictionary<string, string>
            {
                { "name", "ghttp" },
                { "priority", "100" }
            };
            var channel = new GenuineHttpClientChannel(props, null, null);
            ChannelServices.RegisterChannel(channel, false);
        }
        private static void RunClient()
        {
            Console.WriteLine("Connecting to server...");
            RegisterChannel();
          //  WellKnownClientTypeEntry remotetype = new   //WellKnownClientTypeEntry(typeof(POCKnownObjects2.IService),
  //              @"ghttp://localhost/service.rem");
    //        RemotingConfiguration.RegisterWellKnownClientType(remotetype);
           var proxy = (IService)Activator.GetObject(typeof(IService), "ghttp://localhost/service.rem");
            var greeting = proxy.Greeting("World");  // HANGS here
            Console.WriteLine("Server replies: {0}", greeting);
            Console.WriteLine("Press ENTER to quit.");
            Console.ReadLine();
        }

**Comment by yallie** [comment] 2017-04-25 21:01
I think, this is the reason:

>GHTTP Server Connection Manager **works only inside IIS** and accepts connections established by GHTTP Client Connection Manager or GXHTTP Connection Manager. 

— see the Programming Guide, page 69. I haven't ever used IIS as a host, so I hardly can be of any help setting it up.  

For self-hosted servers, I believe only GXHTTP can be used. It should be fully compatible with GHTTP (encoding, wire format, etc) — see page 89.

On the good side, the server GXHTTP channel allows specifying the port via configuration properties. On the bad side, the client channel doesn't support web proxies and HTTP authorization (do you really need these?)

Here is the working application using GXHTTP channel:
https://gist.github.com/yallie/090b69bb3ed15580a0547c81fc6a36c5

Feel free to adapt it to your needs, it's public domain :)

**Comment by yallie** [comment] 2017-04-25 21:08
By the way, according to the guide you can freely mix GXHTTP server with GHTTP client, in case you need to support web proxies, etc. It indeed works, but looks like establishing the connection is noticeably slower (I haven't benchmarked it though, so you'd better try measuring it yourself). Here is another demo gist:

https://gist.github.com/yallie/305d62fe7ec166e516e1d7cd3ac77c02

**Comment by yallie** [comment] 2017-04-27 13:51
I'm closing the issue, but feel free to ask further questions and/or reopen as needed. Cheers!

**Closed as completed by yallie** 2017-04-27 13:51 UTC

**Comment by 3green** [comment] 2017-04-28 12:40
Ok thanks Yallie, will check that material ( gxhttp ) out.
Was trying to get ghttp working on IISExpress ( VS2015 ) but it is hanging on the client at
                        var proxy = (IService)Activator.GetObject(typeof(IService), "ghttp://localhost:62183/service.rem");
var greeting = proxy.Greeting("World"); >> Hangs here

Incidentally, couldn't get GTCP working until in server added a                 
    BinaryClientFormatterSinkProvider clnt = new BinaryClientFormatterSinkProvider();
                var channel = new GenuineTcpChannel(props, clnt, null);

**Comment by 3green** [comment] 2017-04-28 16:14
If launched from a cmd prompt
the GXHTTP server and  GHTTP programs runs OK.

If I launch from VS Debug mode I get the client hanging when calling
var greeting = proxy.Greeting("World");

**Comment by 3green** [comment] 2017-04-29 09:16
Thats interesting, do I need to set some security permissions to get this to work?
            WellKnownServiceTypeEntry WKSTE = new WellKnownServiceTypeEntry(typeof(IService), 
                "ghttp://localhost:8737/Service.rem", WellKnownObjectMode.Singleton);
            RemotingConfiguration.RegisterWellKnownServiceType(WKSTE);
            bool isPOC = RemotingConfiguration.IsActivationAllowed(typeof(IService)); >> getting false here

**Comment by yallie** [comment] 2017-04-29 15:05
Hello,

that's hard to say... Frankly speaking, I haven't used neither IIS/IISExpress, nor client-activated objects. As for permissions, as far as I know, modern frameworks can [switch on legacy CAS policies](https://msdn.microsoft.com/en-us/library/dd409253(v=vs.110).aspx), so you can try it out and check if it helps.

My current plan with Genuine Channels is to get rid of the obsolete stuff, remove extra dependencies such as SharpZipLib, add some unit tests and to make sure the stuff works fine on modern versions of the .NET Framework. My current work on GC takes place at a [separate repository](https://github.com/zyanfx/GenuineChannels), and I'm going to push my updates to this repo once I have something ready.

If you're developing an app with Genuine Channels, I'll be glad if you share your findings as code snippets and/or wiki pages. I think that GC is an awesome library, and deserves to be revived back to life. So if you're interested, please join the project and share what you've found. I'll try my best to help you with further issues, if it's in my competence.

**Comment by 3green** [comment] 2017-04-29 18:50
What am interested in is getting it running/or equiv functionality  on Xamarin pcl

**Comment by yallie** [comment] 2017-04-29 19:00
What made you think it might work on Xamarin?
It's a desktop library abandoned by its authors more than 10 years ago.
Although a brilliant one, but nonetheless very aged.

**Comment by yallie** [comment] 2017-04-29 19:02
Perhaps it *can* be ported to Xamarin, I've never tried that.
But I'm almost certain that it should involve quite a lot of work.

**Comment by 3green** [comment] 2017-04-29 19:19
The current WCF functionality is lacking.
Your  Zyan framework, does it work on the pcl or the .droid project?

**Comment by yallie** [comment] 2017-04-29 19:38
Zyan works on Xamarin, but only on non-PCL projects (full .NET framework is required).

But if you're planning to port your app to iOS in the nearby future, perhaps you should better look for alternative approach. I currently don't have any plans for the iOS port of Zyan.

**Comment by 3green** [comment] 2017-04-29 19:42
Hmmn interesting, looking at droid and UWP?

**Comment by 3green** [comment] 2017-04-29 19:45
Can we have a chat out of public domain about this?

**Comment by yallie** [comment] 2017-04-29 19:52
My email is yallie@yandex.ru, skype nickname is yalgol.

I'm not sure about UWP. 
If your application can be built using full .NET, then that's fine, it can use Zyan. 
But if it's PCL or .NET Core, then — no, Zyan isn't an option.

**Comment by 3green** [comment] 2017-04-29 19:54
Thanks Yallie, will get in touch
